spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql:your_database_url} # Replace "your_database_url" with your actual database url
    username: ${JDBC_DATABASE_USERNAME:your_database_username} # Replace "your_database_username" with your actual database username
    password: ${JDBC_DATABASE_PASSWORD:your_database_password} # Replace "your_database_password" with your actual database password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        type:
          preferred_uuid_jdbc_type: CHAR
  data:
    redis:
      username: default
      password: your_redis_password # Replace "your_redis_password" with your actual Redis password
      port: 8080 # Replace "your_redis_port" with your actual Redis port
      host: your_redis_host # Replace "your_redis_host" with your actual Redis hostname
      database: 0 # Replace with your actual Redis database index
      url: your_redis_endpoint # Replace with your actual Redis endpoint
  cloud:
    azure:
      storage:
        blob:
          account-name: your_azure_storage_account_name # Replace with your Azure storage account name
          account-key: your_azure_storage_account_key # Replace with your Azure storage account key
          container-name: your_azure_blob_container_name # Replace with your Azure blob container name that you store images
server:
  port: ${PORT:your_server_port} # Replace "your_server_port" with your actual server port

azure:
  connection-string: # Replace with your Azure storage account connection string
  image-container-name: your_image_container_name # Replace with your image container name
  product-image-not-found: # Replace with your chosen "image not found" url, you can find a random image on the internet

application:
  security:
    jwt:
      secret-key: # Replace with your secrect key, you can make it with online service that provides secrey key generation
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
